language: ruby

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - bundle install

script: bundle exec jekyll build

deploy:
  provider: s3
  access_key_id: "$DEPLOYER_ACCESS_KEY"
  secret_access_key: "$DEPLOYER_SECRET_KEY"
  bucket: "staging.apps.appizy.com"
  upload-dir: _site
  region: eu-west-1
  skip_cleanup: true
  on:
    branch: feat/ssl

sudo: false
